---
name: Release
on: null
push: null
branches:
  - main
workflow_dispatch: null
permissions: null
contents: read
packages: write
jobs: null
publish: null
runs-on: ubuntu-latest
steps:
  - name: Checkout
uses: actions/checkout@v4
