  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 20
      registry-url: https://npm.pkg.github.com
      scope: '@banatel'
      cache: 'pnpm'

  - name: Enable Corepack
    run: corepack enable

  - name: Install
    run: pnpm install --frozen-lockfile=false

  - name: Build
    run: pnpm run build

  - name: Publish
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: pnpm publish --no-git-checks
